# fly.toml app configuration file generated for polyauxapi on 2023-08-25T01:12:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "polyauxapi"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT=3000